### ISSUE TITLE
The bar code is missing and cannot be identified completely

### ISSUE THREAD

**Issue by zouxianbincc** [shaxxx/flutter_barcode_listener#1]
Hello
I'm glad to find your open source project
However, during the testing process,
The bar code is missing and cannot be identified completely

**Comment by shaxxx** [comment]
Not sure what exactly is the problem?
Is barcode missing or is it not identified completely? These are two distinct cases.
If you're missing part of the barcode have you tried to specify `bufferDuration ` parameter to something longer, IE. 500 ms?

**Comment by zouxianbincc** [comment]
Bar code missing
Correct: 6901028225168
Identified: 690028225158
There are fewer digits in the middle

**Comment by shaxxx** [comment]
Have you tried modifing bufferDuration parameter?

pon, 1. ožu 2021. 10:21 zouxianbincc <notifications@github.com> je napisao:

**Comment by zouxianbincc** [comment]
const Duration aSecond = Duration(seconds: 1);
const Duration hundredMs = Duration(milliseconds: 500);
const int lineFeed = 10;

我改了hundredMs=500
但是测试结果，还是一样。
数字还是出现缺失

**Comment by zouxianbincc** [comment]
Thank you very much.
After testing, change RawKeyUpEvent to RawKeyDownEvent
It can be correctly identified

**Comment by zouxianbincc** [comment]
void _keyBoardCallback(RawKeyEvent keyEvent) {
    if (keyEvent.logicalKey.keyId > 255 &&
        keyEvent.data.logicalKey != LogicalKeyboardKey.enter) return;
    if (keyEvent is RawKeyDownEvent) {
      if (keyEvent.data != null) {
        if (keyEvent.data is RawKeyEventDataAndroid) {
          _controller.sink.add(((keyEvent.data) as RawKeyEventDataAndroid).codePoint);
        } else if (keyEvent.data is RawKeyEventDataFuchsia) {
          _controller.sink
              .add(((keyEvent.data) as RawKeyEventDataFuchsia).codePoint);
        } else if (keyEvent.data.logicalKey == LogicalKeyboardKey.enter) {
          _controller.sink.add(lineFeed);
        }
      } else {
        _controller.sink.add(keyEvent.logicalKey.keyId);
      }
    }
  }

**Comment by shaxxx** [comment]
Glad it worked. If you check history you'll see I started with KeyDown but moved to KeyUp because there were some issues. 
Don't remember why anymore.
