### ISSUE TITLE
null return

### ISSUE THREAD

**Issue by maciogg** [shaxxx/flutter_barcode_listener#18]
I have screen with TextEdit.
When enter screen and scan, plugin gives proper barcode on  method - is OK
When enter TextEdit and scan, plugin put barcode to TextEdit- is OK
When leave TextEdit (no focus) and scan, plugin returns NULL

**Comment by shaxxx** [comment]
Something still has primary focus that handles key strokes.

**Comment by shaxxx** [comment]
No response.
