### ISSUE TITLE
Soft Keyboard

### ISSUE THREAD

**Issue by periklis-periklis** [shaxxx/flutter_barcode_listener#19]
App works great! 

We would like to disable the soft keyboard from appearing when we are in a 'scanning' screen using the package to capture barcodes.  Can we disable the soft keyboard from appearing within the package when a scan occurs?  

Thanks for your time.

**Comment by shaxxx** [comment]
> Can we disable the soft keyboard from appearing within the package when a scan occurs?

No

**Comment by trapeye** [comment]
this have alternative solution?
