### ISSUE TITLE
Modifier keys detection

### ISSUE THREAD

**Issue by samuelbednarcik** [shaxxx/flutter_barcode_listener#20]
OS: Android

If I create a QR code with text **MIK.SUZ.SKO.0140.0001**, it returns wrong characters ( **>** instead of **.** char ). It probably thinks that the SHIFT key is still pressed. For now, I solved the issue by using **plainCodePoint** instead of **codePoint** property on **RayKeyboardAndroid** object and calling uppercase on scanned code.

I don't know how this should be handled, if I use the scanner when focused on some input, it writes correct code.

**Comment by SchrodingersGat** [comment]
I think this is the same issue as https://github.com/shaxxx/flutter_barcode_listener/issues/41

**Comment by shaxxx** [comment]
Please check new version.
