### ISSUE TITLE
Not responding at all

### ISSUE THREAD

**Issue by Inventrax69** [shaxxx/flutter_barcode_listener#27]
I am using trying to run your example in my external handheld device, It is not even populating anything

**Comment by Inventrax69** [comment]
I am using this example with cipher labs rk25 (internal scanner) it is not even firing can some one help me to read qr code using internal scanner

**Comment by selmaskopljakovic** [comment]
You probably should set up the device. For me, that was to enable Keystroke at Settings for Keyence device.
Experiment with the code, to see what data you can get. It is the only way, there is no one solution for every device.
Good luck
