### ISSUE TITLE
only reading Lowercase on android.

### ISSUE THREAD

**Issue by baconjuggling** [shaxxx/flutter_barcode_listener#31]
Scanning QR codes on android is returning the barcodes value, but only  in lowercase, I've had a little play but cant seem to find a fix, any ideas?

**Comment by danielroek** [comment]
I think the scanner probably send the small letter with a `shift-key modifier`. This is what makes this library a bit hard to generalize, every scanner is different and we can't really support anything else than UTF-8.

**Comment by baconjuggling** [comment]
I made a basic fix for my project, that could potentially be implemented, perhaps with a optional caseSenstive: bool parameter.

**Comment by BangPei** [comment]
@baconjuggling hi, can u share me the code?
i've tried to uppercase the character but doesnt work.
thank you

**Comment by baconjuggling** [comment]
> @baconjuggling hi, can u share me the code?
> i've tried to uppercase the character but doesnt work.
> thank you

It's available on my fork.
it's currently only a fix for android though.

**Comment by BangPei** [comment]
> > @baconjuggling hi, can u share me the code?
> > i've tried to uppercase the character but doesnt work.
> > thank you
> 
> It's available on my fork. it's currently only a fix for android though.

Thanks, i will try it.

**Comment by shaxxx** [comment]
Closed due to lack of feedback.
