### ISSUE TITLE
How to hide keyboard after barcode scan?

### ISSUE THREAD

**Issue by arnzuk** [shaxxx/flutter_barcode_listener#32]
Hi

How to hide keyboard after barcode scan?

**Comment by shaxxx** [comment]
This question is out of scope for this plugin. 
There is no need for keyboard to be shown at all to use this plugin.

**Comment by patelnirav48** [comment]
@shaxxx Currently after scan it scan the barcode but it opens the keybord.

**Comment by PraveenGangula1392** [comment]
@shaxxx 
When we do not put focus on any text field and scan everything works perfectly. But let's say i have a text field in my form i entered some data and then scan a barcode then the keyboard shows up, even after i tap outside the text field and scan still the keyboard shows up..

**Comment by niravp-cliqbux** [comment]
@PraveenGangula1392 In my case, i don't even put focus on textfield but it still shows keyboard. Could you suggest what you did for that? Thanks
