### ISSUE TITLE
Need device information

### ISSUE THREAD

**Issue by lucreck** [shaxxx/flutter_barcode_listener#38]
I use multi barcode scanners, so I want to know barcode scanned by what device.
So how I get the device info.
Thank you.

**Comment by SeanKD** [comment]
on the zebra (MC3300) scanner I have onBarcodeScanned method does not trigger at first but if i close the app and reopen it it works fine, did you come up with a fix for this?

**Comment by fgarcia78** [comment]
We're having a similar problem: the components scans just one code and it gets corrupted (the widget resets any customization, like background color); the only way to make it work again is reopening the app.

I want to debug the app from a real device (Android tablet) to try to identify the problem that is happening, but I haven't had the time yet.

**Comment by SeanKD** [comment]
@fgarcia78 any luck with this?

**Comment by shaxxx** [comment]
No feedback.

**Comment by rymesaint** [comment]
is there any update on this?
