### ISSUE TITLE
Barcode result is empty in Flutter Desktop

### ISSUE THREAD

**Issue by fathah** [shaxxx/flutter_barcode_listener#4]
Thanks for this wonderful package, however when I tried to work with Flutter Desktop, it doesn't provide any bar code as response. It's empty. Let me know if there's any fixes. 

Thanks

**Comment by shaxxx** [comment]
At the time this plugin was made there was no Web or Desktop platforms.
Logic of the plugin should work with any platform, as long as underlaying key events are hooked.
So in order to handle other platforms `_keyBoardCallback` need to include additional platforms.
PR's are welcome.

**Comment by danielroek** [comment]
PR with web and desktop support has been merged @rshrc @fathah

**Comment by fathah** [comment]
@danielroek thanks man. It's a great job
