### ISSUE TITLE
Barcode sometimes returned truncated from the beginning of the line

### ISSUE THREAD

**Issue by al-bezd** [shaxxx/flutter_barcode_listener#40]
The barcode sometimes returns truncated from the beginning of the line, despite the fact that this does not always happen, but sometimes, out of 5 scans, only 2 are successful

**Comment by al-bezd** [comment]
I solved the problem myself, thanks everyone

**Comment by xyl-san** [comment]
Hello sir, can you give some details as to how you fixed this bug?
