### ISSUE TITLE
Scanned barcodes and qr codes is in lowercase

### ISSUE THREAD

**Issue by davepot04** [shaxxx/flutter_barcode_listener#41]
![viber_image_2023-06-06_19-28-58-028](https://github.com/shaxxx/flutter_barcode_listener/assets/100922481/e26b808d-6f12-4b2c-823d-e6ad6a7cdcff)

values of scanned barcodes and qr codes are all in lower case but when I don't use the package and only used a TextFormField the value is correct, i think it can't detect the if the keyevent has a shift key pressed with other character

(sorry for my bad english 😅)

**Comment by fuadreza** [comment]
Hi @davepot04 , 

I made an update for the scanned character to be case sensitive You can see on my forked version here:

https://github.com/fuadreza/flutter_barcode_listener

**Comment by SchrodingersGat** [comment]
> Hi @davepot04 ,
> 
> I made an update for the scanned character to be case sensitive You can see on my forked version here:
> 
> https://github.com/fuadreza/flutter_barcode_listener

@fuadreza it works really well - any chance you will be pushing to https://pub.dev/ ?

**Comment by fuadreza** [comment]
I have already open PR #44 , but it seems this package maintainer haven't responded yet.

**Comment by SchrodingersGat** [comment]
Yeah, no updates since March last year, might be dead?

**Comment by shaxxx** [comment]
Well, it's not so simple as you might think.
Plugin is used by many people and if current working condition changes it's a breaking change, and people hate breaking changes.
I'm simply waiting for feedback, and as things are, not many people are requesting this.
Beside, you don't need pub.dev, you can always specify direct git link in your pubspec.yaml.

With all this said, just fix PR and I'll merge it.

**Comment by SchrodingersGat** [comment]
@shaxxx all fair points, hope I didn't come across poorly :)

**Comment by fuadreza** [comment]
> Well, it's not so simple as you might think. Plugin is used by many people and if current working condition changes it's a breaking change, and people hate breaking changes. I'm simply waiting for feedback, and as things are, not many people are requesting this. Beside, you don't need pub.dev, you can always specify direct git link in your pubspec.yaml.
> 
> With all this said, just fix PR and I'll merge it.

Oh I see, I will add some option to make it optional and won't break changes.

**Comment by shaxxx** [comment]
Added in 0.1.4

**Comment by PraveenGangula1392** [comment]
For me the issue is vice-versa , on scan ; is getting converted to : 
Example S24-00318;A

Output   S24-00318:A
