### ISSUE TITLE
Listening unwanted screen

### ISSUE THREAD

**Issue by SMBilalCS** [shaxxx/flutter_barcode_listener#53]
i wrap first screen with barcode listener, but when i navigate to second screen barcode listener is also listening there.

**Comment by shaxxx** [comment]
Have you seen example project?

**Comment by SMBilalCS** [comment]
> Have you seen example project?

yes, i made 3 screens. I use barcodelistener on 2nd screen. so in first screen it is not listening which is fine. in second its listening but in third screen its also listening but i dont wont it to listen.

**Comment by shaxxx** [comment]
Again, example has everything you need. Notice visible variable on first screen.
